//
//  Verb.swift
//  IrishVocabulary
//
//  Created by Scott on 5/31/17.
//  Copyright © 2017 Scott. All rights reserved.
//

import Foundation
import RealmSwift

class Verb : Object {
    
    
    dynamic var infinitive = ""
    dynamic var english = ""
    dynamic var verbalAdjective = ""
    dynamic var verbalNoun = ""
    
    dynamic var simplePast1stPersonSingPos = ""
    dynamic var simplePast1stPersonSingInter = ""
    dynamic var simplePast1stPersonSingNeg = ""
    dynamic var simplePast2ndPersonSingPos = ""
    dynamic var simplePast2ndPersonSingInter = ""
    dynamic var simplePast2ndPersonSingNeg = ""
    dynamic var simplePast3rdPersonSingPos = ""
    dynamic var simplePast3rdPersonSingInter = ""
    dynamic var simplePast3rdPersonSingNeg = ""
    dynamic var simplePast1stPersonPlPosAlt = ""
    dynamic var simplePast1stPersonPlInterAlt = ""
    dynamic var simplePast1stPersonPlNegAlt = ""
    dynamic var simplePast1stPersonPlPos = ""
    dynamic var simplePast1stPersonPlInter = ""
    dynamic var simplePast1stPersonPlNeg = ""
    dynamic var simplePast2ndPersonPlPos = ""
    dynamic var simplePast2ndPersonPlInter = ""
    dynamic var simplePast2ndPersonPlNeg = ""
    dynamic var simplePast3rdPersonPlPos = ""
    dynamic var simplePast3rdPersonPlInter = ""
    dynamic var simplePast3rdPersonPlNeg = ""
    dynamic var simplePast3rdPersonPlPosAlt = ""
    dynamic var simplePast3rdPersonPlInterAlt = ""
    dynamic var simplePast3rdPersonPlNegAlt  = ""
    dynamic var simplePastImpersonalPos = ""
    dynamic var simplePastImpersonalInter = ""
    dynamic var simplePastImpersonalNeg = ""
    
    dynamic var present1stPersonSingPos = ""
    dynamic var present1stPersonSingInter = ""
    dynamic var present1stPersonSingNeg = ""
    dynamic var present2ndPersonSingPos = ""
    dynamic var present2ndPersonSingInter = ""
    dynamic var present2ndPersonSingNeg = ""
    dynamic var present3rdPersonSingPos = ""
    dynamic var present3rdPersonSingInter = ""
    dynamic var present3rdPersonSingNeg = ""
    dynamic var present1stPersonPlPosAlt = ""
    dynamic var present1stPersonPlInterAlt = ""
    dynamic var present1stPersonPlNegAlt = ""
    dynamic var present1stPersonPlPos = ""
    dynamic var present1stPersonPlInter = ""
    dynamic var present1stPersonPlNeg = ""
    dynamic var present2ndPersonPlPos = ""
    dynamic var present2ndPersonPlInter = ""
    dynamic var present2ndPersonPlNeg = ""
    dynamic var present3rdPersonPlPos = ""
    dynamic var present3rdPersonPlInter = ""
    dynamic var present3rdPersonPlNeg = ""
    dynamic var presentImpersonalPos = ""
    dynamic var presentImpersonalInter = ""
    dynamic var presentImpersonalNeg = ""
    
    dynamic var future1stPersonSingPos = ""
    dynamic var future1stPersonSingInter = ""
    dynamic var future1stPersonSingNeg = ""
    dynamic var future2ndPersonSingPos = ""
    dynamic var future2ndPersonSingInter = ""
    dynamic var future2ndPersonSingNeg = ""
    dynamic var future3rdPersonSingPos = ""
    dynamic var future3rdPersonSingInter = ""
    dynamic var future3rdPersonSingNeg = ""
    dynamic var future1stPersonPlPosAlt = ""
    dynamic var future1stPersonPlInterAlt = ""
    dynamic var future1stPersonPlNegAlt = ""
    dynamic var future1stPersonPlPos = ""
    dynamic var future1stPersonPlInter = ""
    dynamic var future1stPersonPlNeg = ""
    dynamic var future2ndPersonPlPos = ""
    dynamic var future2ndPersonPlInter = ""
    dynamic var future2ndPersonPlNeg = ""
    dynamic var future3rdPersonPlPos = ""
    dynamic var future3rdPersonPlInter = ""
    dynamic var future3rdPersonPlNeg = ""
    dynamic var futureImpersonalPos = ""
    dynamic var futureImpersonalInter = ""
    dynamic var futureImpersonalNeg = ""
    
    dynamic var conditional1stPersonSingPos = ""
    dynamic var conditional1stPersonSingInter = ""
    dynamic var conditional1stPersonSingNeg = ""
    dynamic var conditional2ndPersonSingPos = ""
    dynamic var conditional2ndPersonSingInter = ""
    dynamic var conditional2ndPersonSingNeg = ""
    dynamic var conditional3rdPersonSingPos = ""
    dynamic var conditional3rdPersonSingInter = ""
    dynamic var conditional3rdPersonSingNeg = ""
    dynamic var conditional1stPersonPlPosAlt = ""
    dynamic var conditional1stPersonPlInterAlt = ""
    dynamic var conditional1stPersonPlNegAlt = ""
    dynamic var conditional1stPersonPlPos = ""
    dynamic var conditional1stPersonPlInter = ""
    dynamic var conditional1stPersonPlNeg = ""
    dynamic var conditional2ndPersonPlPos = ""
    dynamic var conditional2ndPersonPlInter = ""
    dynamic var conditional2ndPersonPlNeg = ""
    dynamic var conditional3rdPersonPlPosAlt = ""
    dynamic var conditional3rdPersonPlInterAlt = ""
    dynamic var conditional3rdPersonPlNegAlt = ""
    dynamic var conditional3rdPersonPlPos = ""
    dynamic var conditional3rdPersonPlInter = ""
    dynamic var conditional3rdPersonPlNeg = ""
    dynamic var conditionalImpersonalPos = ""
    dynamic var conditionalImpersonalInter = ""
    dynamic var conditionalImpersonalNeg = ""
    
    dynamic var habitualPast1stPersonSingPos = ""
    dynamic var habitualPast1stPersonSingInter = ""
    dynamic var habitualPast1stPersonSingNeg = ""
    dynamic var habitualPast2ndPersonSingPos = ""
    dynamic var habitualPast2ndPersonSingInter = ""
    dynamic var habitualPast2ndPersonSingNeg = ""
    dynamic var habitualPast3rdPersonSingPos = ""
    dynamic var habitualPast3rdPersonSingInter = ""
    dynamic var habitualPast3rdPersonSingNeg = ""
    dynamic var habitualPast1stPersonPlPosAlt = ""
    dynamic var habitualPast1stPersonPlInterAlt = ""
    dynamic var habitualPast1stPersonPlNegAlt = ""
    dynamic var habitualPast1stPersonPlPos = ""
    dynamic var habitualPast1stPersonPlInter = ""
    dynamic var habitualPast1stPersonPlNeg = ""
    dynamic var habitualPast2ndPersonPlPos = ""
    dynamic var habitualPast2ndPersonPlInter = ""
    dynamic var habitualPast2ndPersonPlNeg = ""
    dynamic var habitualPast3rdPersonPlPosAlt = ""
    dynamic var habitualPast3rdPersonPlInterAlt = ""
    dynamic var habitualPast3rdPersonPlNegAlt = ""
    dynamic var habitualPast3rdPersonPlPos = ""
    dynamic var habitualPast3rdPersonPlInter = ""
    dynamic var habitualPast3rdPersonPlNeg = ""
    dynamic var habitualPastImpersonalPos = ""
    dynamic var habitualPastImpersonalInter = ""
    dynamic var habitualPastImpersonalNeg = ""
    
    dynamic var imperative1stPersonSingPos = ""
    dynamic var imperative1stPersonSingNeg = ""
    dynamic var imperative2ndPersonSingPos = ""
    dynamic var imperative2ndPersonSingNeg = ""
    dynamic var imperative3rdPersonSingPos = ""
    dynamic var imperative3rdPersonSingNeg = ""
    dynamic var imperative1stPersonPlPos = ""
    dynamic var imperative1stPersonPlNeg = ""
    dynamic var imperative1stPersonPlPosAlt = ""
    dynamic var imperative1stPersonPlNegAlt = ""
    dynamic var imperative2ndPersonPlPos = ""
    dynamic var imperative2ndPersonPlNeg = ""
    dynamic var imperative3rdPersonPlPos = ""
    dynamic var imperative3rdPersonPlNeg = ""
    dynamic var imperative3rdPersonPlPosAlt = ""
    dynamic var imperative3rdPersonPlNegAlt = ""
    dynamic var imperativeImpersonalPos = ""
    dynamic var imperativeImpersonalNeg = ""
    
    dynamic var presentSubjunctive1stPersonSingPos = ""
    dynamic var presentSubjunctive1stPersonSingNeg = ""
    dynamic var presentSubjunctive2ndPersonSingPos = ""
    dynamic var presentSubjunctive2ndPersonSingNeg = ""
    dynamic var presentSubjunctive3rdPersonSingPos = ""
    dynamic var presentSubjunctive3rdPersonSingNeg = ""
    dynamic var presentSubjunctive1stPersonPlPos = ""
    dynamic var presentSubjunctive1stPersonPlNeg = ""
    dynamic var presentSubjunctive1stPersonPlPosAlt  = ""
    dynamic var presentSubjunctive1stPersonPlNegAlt  = ""
    dynamic var presentSubjunctive2ndPersonPlPos = ""
    dynamic var presentSubjunctive2ndPersonPlNeg = ""
    dynamic var presentSubjunctive3rdPersonPlPos = ""
    dynamic var presentSubjunctive3rdPersonPlNeg = ""
    dynamic var presentSubjunctiveImpersonalPos = ""
    dynamic var presentSubjunctiveImpersonalNeg = ""
    
    
    
    
}
